import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-100`}
      >
        <Navbar />
        {children}
        {/* <footer className="text-center text-slate-400 pb-2">
          <p>&copy; 2026 School Clinic System</p>
          <a href="/privacy-policy">Privacy Policy {" | "}</a>  
          <a href="/terms-of-service">Terms of Service</a>
        </footer> */}
      </body>
    </html>
  );
}
